### ISSUE TITLE
Any schedule to release the code?

### ISSUE THREAD

**Issue by ruili3** [Isabella98Liu/DG-Mesh#1]
Hey Isabella,

Thanks for sharing the great work! Do you have any schedules to release the code? It would be great if you set an approximate time so we can stay tuned and follow up in time!

Thanks a lot !

**Comment by antithing** [comment]
+1

**Comment by Isabella98Liu** [comment]
Hi @ruili3 and @antithing, thank you for showing interest in our work! We plan to release the code upon the paper's acceptance. :)
