### ISSUE TITLE
Question on how trainable color can be defined per vertex, while there are varying number of vertices for every iteration during mesh optimization.

### ISSUE THREAD

**Issue by deepshwang** [Isabella98Liu/DG-Mesh#3]
Hi, Thanks for the great work!

I was reading your work, and wondered how nvdiffrast can be actually implemented to render an image from a mesh that is being trained.

From my understanding, mesh from DPSR + Diff.MC during optimization can have varying number of vertices for every iteration.

In this case, how can a trainable color be defined for each vertex for every iteration?

Thank you in advance.

**Comment by Isabella98Liu** [comment]
Hi @deepshwang, sorry for the late reply, and thanks for your interest in our work! We optimize the vertex colors through an MLP, which takes the position of the vertices as input and outputs the RGB colors.
